#!/usr/bin/env python3
"""Generate source/gen3_records.c from PKHeX's Generation III record IDs.

The games keep a block of 32-bit counters - steps taken, battles won, eggs
hatched and so on - and the meaning of each index differs per game. PKHeX
names them in the RecID3RuSa, RecID3Emerald and RecID3FRLG enums in
PKHeX.Core/Saves/Substructures/Gen3/Record3.cs.

Usage: tools/build_records.py <path to a PKHeX checkout>
"""
from __future__ import annotations
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "source" / "gen3_records.c"
ENUMS = {"RecID3RuSa": "rs", "RecID3Emerald": "emerald", "RecID3FRLG": "frlg"}


def parse(text: str, enum: str) -> list[str]:
    body = text.split(f"public enum {enum}", 1)[1]
    body = body.split("{", 1)[1].split("}", 1)[0]
    entries: dict[int, str] = {}
    for name, value in re.findall(r"(\w+)\s*=\s*(\d+)\s*,?", body):
        entries[int(value)] = name
    # The last entry is how many counters the block holds, not a record. It can
    # be larger than the highest named one: PKHeX leaves the tail unnamed, and
    # the block still reserves those slots.
    total = max(entries)
    if entries.pop(total, None) != "NUM_GAME_STATS":
        raise SystemExit(f"{enum}: expected NUM_GAME_STATS last")
    return [title(entries.get(i, f"Unknown_{i}")) for i in range(total)]


def title(name: str) -> str:
    """PKHeX shows these title-cased with underscores as spaces."""
    return " ".join(w.capitalize() for w in name.split("_"))


def emit(f, tag: str, names: list[str]) -> None:
    f.write(f"static const char *const record_names_{tag}[{len(names)}] = {{\n")
    for i, n in enumerate(names):
        f.write(f'    /* {i:2d} */ "{n}",\n')
    f.write("};\n\n")


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src = (pathlib.Path(sys.argv[1]) / "PKHeX.Core" / "Saves" / "Substructures" / "Gen3"
           / "Record3.cs").read_text(encoding="utf-8")
    tables = {tag: parse(src, enum) for enum, tag in ENUMS.items()}

    with OUT.open("w", encoding="utf-8") as f:
        f.write("/*\n"
                " * Generation III game records: what each 32-bit counter in the record\n"
                " * block means, which differs per game.\n"
                " *\n"
                " * GENERATED by tools/build_records.py from PKHeX's Record3.cs enums.\n"
                " * Do not edit by hand.\n"
                " */\n"
                '#include "gen3.h"\n\n')
        for tag in ("rs", "emerald", "frlg"):
            emit(f, tag, tables[tag])
        f.write("""unsigned gen3_record_count(Gen3Game game) {
    switch (game) {
        case GEN3_GAME_EMERALD: return (unsigned)(sizeof record_names_emerald / sizeof record_names_emerald[0]);
        case GEN3_GAME_FRLG:    return (unsigned)(sizeof record_names_frlg / sizeof record_names_frlg[0]);
        default:                return (unsigned)(sizeof record_names_rs / sizeof record_names_rs[0]);
    }
}

const char *gen3_record_name(Gen3Game game, unsigned index) {
    if (index >= gen3_record_count(game)) return "?";
    switch (game) {
        case GEN3_GAME_EMERALD: return record_names_emerald[index];
        case GEN3_GAME_FRLG:    return record_names_frlg[index];
        default:                return record_names_rs[index];
    }
}
""")
    print(f"wrote {OUT} (" + ", ".join(f"{t} {len(n)}" for t, n in tables.items()) + ")")


if __name__ == "__main__":
    main()
