#!/usr/bin/env python3
"""Generate source/gen3_locations.c from PKHeX's Generation III location names.

PKHeX keeps them as one name per line in
PKHeX.Core/Resources/text/locations/gen3/, indexed directly by the met
location byte: text_rsefrlg_00000_en.txt for the cartridge games and
text_cxd_00000_en.txt for Colosseum and XD.

Usage: tools/build_locations.py <path to a PKHeX checkout>
"""
from __future__ import annotations
import pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "source" / "gen3_locations.c"


def load(path: pathlib.Path) -> list[str]:
    lines = path.read_text(encoding="utf-8").split("\n")
    # A trailing newline yields one empty element; drop only that.
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def emit(f, name: str, names: list[str]) -> None:
    f.write(f"static const char *const {name}[{len(names)}] = {{\n")
    for i, n in enumerate(names):
        escaped = n.replace("\\", "\\\\").replace('"', '\\"')
        f.write(f'    /* {i:3d} */ "{escaped}",\n')
    f.write("};\n\n")


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src = pathlib.Path(sys.argv[1]) / "PKHeX.Core" / "Resources" / "text" / "locations" / "gen3"
    gba = load(src / "text_rsefrlg_00000_en.txt")
    cxd = load(src / "text_cxd_00000_en.txt")
    if not (200 <= len(gba) <= 256) or not (200 <= len(cxd) <= 256):
        raise SystemExit(f"unexpected table sizes: {len(gba)} / {len(cxd)}")

    with OUT.open("w", encoding="utf-8") as f:
        f.write("/*\n"
                " * Generation III met location names, indexed by the met location byte.\n"
                " *\n"
                " * GENERATED by tools/build_locations.py from PKHeX's\n"
                " * Resources/text/locations/gen3 tables. Do not edit by hand.\n"
                " *\n"
                " * Several entries name two places because the cartridge games and the\n"
                " * GameCube games reuse indices differently; PKHeX writes both, and so does\n"
                " * this, rather than picking one and being wrong half the time.\n"
                " */\n"
                '#include "gen3.h"\n\n')
        emit(f, "gba_locations", gba)
        emit(f, "cxd_locations", cxd)
        f.write("""const char *gen3_met_location_name(uint8_t location, bool gamecube) {
    const char *const *table = gamecube ? cxd_locations : gba_locations;
    const unsigned count = gamecube
        ? (unsigned)(sizeof cxd_locations / sizeof cxd_locations[0])
        : (unsigned)(sizeof gba_locations / sizeof gba_locations[0]);
    if (location >= count) return "?";
    /* A blank line in the source table means the index is unused. */
    return table[location][0] ? table[location] : "-";
}
""")
    print(f"wrote {OUT} ({len(gba)} cartridge, {len(cxd)} GameCube locations)")


if __name__ == "__main__":
    main()
