#!/usr/bin/env python3
"""Generate source/gen3_event_names.c from PKHeX's Generation III event labels.

The games hold a couple of thousand scripted event flags and a few dozen
event constants per game, and on their own they are just bit indices. PKHeX
ships a label for nearly every one in

    PKHeX.Core/Resources/text/script/gen3/{flags,const}_{rs,e,frlg}_en.txt

as tab-separated `index<TAB>category<TAB>description` lines, where constants
carry a fourth field listing named values. The parsing here follows PKHeX's
EventLabelParsing: the index is decimal unless prefixed (0x for flags, 0x4 for
constants), the category is the first character of the second field, and the
description is everything after the second tab.

Usage: tools/build_event_names.py <path to a PKHeX checkout>
"""
from __future__ import annotations
import pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "source" / "gen3_event_names.c"
GAMES = {"rs": "rs", "e": "emerald", "frlg": "frlg"}

# PKHeX's NamedEventTypeUtil.GetEventType, by its leading character. Anything
# else - including the 'i' used for found-item flags - is None there too.
CATEGORY = {
    "h": "GEN3_EVENT_HIDDEN_ITEM",
    "m": "GEN3_EVENT_MISC",
    "f": "GEN3_EVENT_FLY",
    "t": "GEN3_EVENT_TRAINER",
    "s": "GEN3_EVENT_STORY",
    "a": "GEN3_EVENT_ACHIEVEMENT",
    "+": "GEN3_EVENT_STATISTIC",
    "*": "GEN3_EVENT_USEFUL",
    "e": "GEN3_EVENT_ENCOUNTER",
    "g": "GEN3_EVENT_GIFT",
    "r": "GEN3_EVENT_REBATTLE",
}

# The UI font is ASCII, so the three characters PKHeX's English labels use
# beyond it are spelled out rather than dropped.
TRANSLITERATE = {"é": "e", "♂": "(M)", "♀": "(F)"}


def ascii_only(text: str, where: str) -> str:
    out = []
    for ch in text:
        if ch in TRANSLITERATE:
            out.append(TRANSLITERATE[ch])
        elif 0x20 <= ord(ch) <= 0x7E:
            out.append(ch)
        else:
            raise SystemExit(f"{where}: no ASCII spelling for U+{ord(ch):04X} ({ch!r})")
    return "".join(out)


def parse_index(text: str, prefix: str) -> int:
    if text.startswith(prefix):
        return int(text[len(prefix):], 16)
    return int(text)


def parse(path: pathlib.Path, prefix: str, with_values: bool):
    entries = []
    seen = set()
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        parts = line.split("\t", 2)
        if len(parts) < 3:
            continue
        where = f"{path.name}:{lineno}"
        index = parse_index(parts[0], prefix)
        if index in seen:
            raise SystemExit(f"{where}: duplicate index {index}")
        seen.add(index)
        category = CATEGORY.get(parts[1][:1], "GEN3_EVENT_NONE")

        rest = parts[2]
        values = []
        if with_values:
            desc, _, tail = rest.partition("\t")
            for tuple_text in tail.split(","):
                value, sep, name = tuple_text.partition(":")
                if not sep:
                    break
                values.append((parse_index(value.strip(), "0x"),
                               ascii_only(name.strip(), where)))
        else:
            desc = rest
        entries.append((index, category, ascii_only(desc, where), values))
    entries.sort(key=lambda e: e[0])
    return entries


def c_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_values(out, tag: str, entries) -> None:
    for index, _, _, values in entries:
        if not values:
            continue
        out.write(f"static const Gen3EventValue work_values_{tag}_{index}[] = {{\n")
        for value, name in values:
            out.write(f"    {{ {value}, {c_string(name)} }},\n")
        out.write("};\n")
    out.write("\n")


def emit_table(out, name: str, entries, tag: str | None) -> None:
    out.write(f"static const Gen3EventName {name}[] = {{\n")
    for index, category, desc, values in entries:
        vals = f"work_values_{tag}_{index}" if values else "NULL"
        count = len(values)
        out.write(f"    {{ {index}, {category}, {c_string(desc)}, {vals}, {count} }},\n")
    out.write("};\n\n")


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src = pathlib.Path(sys.argv[1]) / "PKHeX.Core/Resources/text/script/gen3"
    if not src.is_dir():
        raise SystemExit(f"not a PKHeX checkout: {src} missing")

    flags = {tag: parse(src / f"flags_{key}_en.txt", "0x", False)
             for key, tag in GAMES.items()}
    work = {tag: parse(src / f"const_{key}_en.txt", "0x4", True)
            for key, tag in GAMES.items()}

    with OUT.open("w") as out:
        out.write("/*\n"
                  " * Generated by tools/build_event_names.py - do not edit.\n"
                  " *\n"
                  " * Names for the scripted event flags and event constants, from PKHeX's\n"
                  " * Resources/text/script/gen3 label files. Each table is sorted by index so\n"
                  " * a lookup is a binary search; the games leave plenty of indices unnamed,\n"
                  " * and those fall back to the number.\n"
                  " */\n"
                  "#include <stddef.h>\n\n"
                  '#include "gen3_event_names.h"\n\n')

        for tag in ("rs", "emerald", "frlg"):
            emit_values(out, tag, work[tag])
        for tag in ("rs", "emerald", "frlg"):
            emit_table(out, f"flag_names_{tag}", flags[tag], None)
            emit_table(out, f"work_names_{tag}", work[tag], tag)

        out.write("""static const Gen3EventName *find(const Gen3EventName *table, size_t count,
                                unsigned index) {
    size_t low = 0, high = count;
    while (low < high) {
        const size_t mid = low + (high - low) / 2u;
        if (table[mid].index == index) return &table[mid];
        if (table[mid].index < index) low = mid + 1u;
        else high = mid;
    }
    return NULL;
}

#define PICK(kind) \\
    switch (game) { \\
        case GEN3_GAME_EMERALD: return find(kind##_emerald, sizeof kind##_emerald / sizeof kind##_emerald[0], index); \\
        case GEN3_GAME_FRLG:    return find(kind##_frlg,    sizeof kind##_frlg    / sizeof kind##_frlg[0],    index); \\
        case GEN3_GAME_RS:      return find(kind##_rs,      sizeof kind##_rs      / sizeof kind##_rs[0],      index); \\
        default:                return NULL; \\
    }

const Gen3EventName *gen3_event_flag_entry(Gen3Game game, unsigned index) {
    PICK(flag_names)
}

const Gen3EventName *gen3_event_work_entry(Gen3Game game, unsigned index) {
    PICK(work_names)
}

const char *gen3_event_flag_name(Gen3Game game, unsigned index) {
    const Gen3EventName *e = gen3_event_flag_entry(game, index);
    return e ? e->name : NULL;
}

const char *gen3_event_work_name(Gen3Game game, unsigned index) {
    const Gen3EventName *e = gen3_event_work_entry(game, index);
    return e ? e->name : NULL;
}

const char *gen3_event_work_value_name(Gen3Game game, unsigned index, unsigned value) {
    const Gen3EventName *e = gen3_event_work_entry(game, index);
    if (!e) return NULL;
    for (unsigned i = 0; i < e->value_count; ++i)
        if (e->values[i].value == value) return e->values[i].name;
    return NULL;
}

const char *gen3_event_category_name(Gen3EventCategory category) {
    switch (category) {
        case GEN3_EVENT_HIDDEN_ITEM: return "Hidden item";
        case GEN3_EVENT_TRAINER:     return "Trainer";
        case GEN3_EVENT_STORY:       return "Story";
        case GEN3_EVENT_FLY:         return "Fly";
        case GEN3_EVENT_MISC:        return "Misc";
        case GEN3_EVENT_STATISTIC:   return "Statistic";
        case GEN3_EVENT_ACHIEVEMENT: return "Achievement";
        case GEN3_EVENT_USEFUL:      return "Useful";
        case GEN3_EVENT_ENCOUNTER:   return "Encounter";
        case GEN3_EVENT_GIFT:        return "Gift";
        case GEN3_EVENT_REBATTLE:    return "Rebattle";
        default:                     return "";
    }
}
""")

    counts = ", ".join(f"{t} {len(flags[t])}+{len(work[t])}" for t in ("rs", "emerald", "frlg"))
    print(f"wrote {OUT} ({counts})")


if __name__ == "__main__":
    main()
