#!/usr/bin/env python3
"""Generate source/gen3_personal.c from PKHeX's Generation III personal tables.

PKHeX stores one 0x1C-byte record per National Dex number in
PKHeX.Core/Resources/byte/personal/personal_{rs,e,fr,lg}. Only the fields this
port actually shows are emitted: base stats, types, gender ratio and the two
abilities.

The four games agree on everything except Deoxys, whose form - and therefore
base stats - differs per game, so that one entry is emitted per game.

Usage: tools/build_personal.py <path to a PKHeX checkout>
"""
from __future__ import annotations
import pathlib, sys

SIZE = 0x1C
MAX_DEX = 386
OFF = {"hp": 0x00, "atk": 0x01, "def": 0x02, "spe": 0x03, "spa": 0x04, "spd": 0x05,
       "t1": 0x06, "t2": 0x07, "gender": 0x10, "growth": 0x13, "a1": 0x16, "a2": 0x17}
ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "source" / "gen3_personal.c"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    pk = pathlib.Path(sys.argv[1])
    byte = pk / "PKHeX.Core" / "Resources" / "byte" / "personal"
    tabs = {g: (byte / f"personal_{g}").read_bytes() for g in ("rs", "e", "fr", "lg")}
    for g, d in tabs.items():
        if len(d) != (MAX_DEX + 1) * SIZE:
            raise SystemExit(f"personal_{g} is {len(d)} bytes, expected {(MAX_DEX+1)*SIZE}")

    abilities = (pk / "PKHeX.Core" / "Resources" / "text" / "other" / "en"
                 / "text_Abilities_en.txt").read_text(encoding="utf-8").splitlines()

    base = tabs["e"]
    def rec(tab: bytes, dex: int, key: str) -> int:
        return tab[dex * SIZE + OFF[key]]

    # Which species disagree between games on base stats?
    varying = [d for d in range(1, MAX_DEX + 1)
               if len({tuple(tabs[g][d*SIZE:d*SIZE+6]) for g in tabs}) > 1]

    max_ability = max(max(rec(base, d, "a1"), rec(base, d, "a2"))
                      for d in range(1, MAX_DEX + 1))

    L = []
    L.append("/* Generated by tools/build_personal.py from PKHeX's Generation III")
    L.append(" * personal tables. Do not edit by hand; see SOURCES.md. */")
    L.append('#include "gen3_personal.h"')
    L.append("")
    L.append(f"const Gen3Personal gen3_personal_table[{MAX_DEX + 1}] = {{")
    for dex in range(0, MAX_DEX + 1):
        v = [rec(base, dex, k) for k in ("hp","atk","def","spe","spa","spd","t1","t2",
                                         "gender","growth","a1","a2")]
        L.append("    { " + ", ".join(f"{x:3d}" for x in v) + " },")
    L.append("};")
    L.append("")
    L.append("/* Deoxys is the one species whose base stats differ per game, because")
    L.append(" * its form does. Order: Ruby/Sapphire, Emerald, FireRed, LeafGreen.")
    L.append(" * include/gen3_personal.h pins its dex number as GEN3_PERSONAL_VARYING_DEX;")
    L.append(f" * this build found {varying}. */")
    L.append("const uint8_t gen3_personal_deoxys[4][6] = {")
    for g in ("rs", "e", "fr", "lg"):
        d = varying[0] if varying else 0
        L.append("    { " + ", ".join(f"{tabs[g][d*SIZE+i]:3d}" for i in range(6)) + " },")
    L.append("};")
    L.append("")
    L.append(f"const char *const gen3_ability_names[{max_ability + 1}] = {{")
    for i in range(max_ability + 1):
        name = abilities[i] if i < len(abilities) else "?"
        if name == "—":
            name = "(none)"
        L.append(f'    "{name}",')
    L.append("};")
    L.append(f"const unsigned gen3_ability_name_count = {max_ability + 1}u;")
    L.append("")

    OUT.write_text("\n".join(L), encoding="ascii")
    print(f"personal: wrote {OUT.relative_to(ROOT)} "
          f"({MAX_DEX + 1} species, {max_ability + 1} abilities, "
          f"per-game entry for dex {varying})")


if __name__ == "__main__":
    main()
