/*
 * Generated by tools/build_names.py - do not edit.
 *
 * Move, item and species names, straight from PKHeX's name lists so they
 * cannot drift out of step with it. Colosseum and XD add their own key
 * items on top of the cartridge list, starting at id 500.
 */
#include "gen3.h"
#include "gen3_all.h"

static const char *const move_names[] = {
    "-", "Pound", "Karate Chop", "Double Slap",
    "Comet Punch", "Mega Punch", "Pay Day", "Fire Punch",
    "Ice Punch", "Thunder Punch", "Scratch", "Vise Grip",
    "Guillotine", "Razor Wind", "Swords Dance", "Cut",
    "Gust", "Wing Attack", "Whirlwind", "Fly",
    "Bind", "Slam", "Vine Whip", "Stomp",
    "Double Kick", "Mega Kick", "Jump Kick", "Rolling Kick",
    "Sand Attack", "Headbutt", "Horn Attack", "Fury Attack",
    "Horn Drill", "Tackle", "Body Slam", "Wrap",
    "Take Down", "Thrash", "Double-Edge", "Tail Whip",
    "Poison Sting", "Twineedle", "Pin Missile", "Leer",
    "Bite", "Growl", "Roar", "Sing",
    "Supersonic", "Sonic Boom", "Disable", "Acid",
    "Ember", "Flamethrower", "Mist", "Water Gun",
    "Hydro Pump", "Surf", "Ice Beam", "Blizzard",
    "Psybeam", "Bubble Beam", "Aurora Beam", "Hyper Beam",
    "Peck", "Drill Peck", "Submission", "Low Kick",
    "Counter", "Seismic Toss", "Strength", "Absorb",
    "Mega Drain", "Leech Seed", "Growth", "Razor Leaf",
    "Solar Beam", "Poison Powder", "Stun Spore", "Sleep Powder",
    "Petal Dance", "String Shot", "Dragon Rage", "Fire Spin",
    "Thunder Shock", "Thunderbolt", "Thunder Wave", "Thunder",
    "Rock Throw", "Earthquake", "Fissure", "Dig",
    "Toxic", "Confusion", "Psychic", "Hypnosis",
    "Meditate", "Agility", "Quick Attack", "Rage",
    "Teleport", "Night Shade", "Mimic", "Screech",
    "Double Team", "Recover", "Harden", "Minimize",
    "Smokescreen", "Confuse Ray", "Withdraw", "Defense Curl",
    "Barrier", "Light Screen", "Haze", "Reflect",
    "Focus Energy", "Bide", "Metronome", "Mirror Move",
    "Self-Destruct", "Egg Bomb", "Lick", "Smog",
    "Sludge", "Bone Club", "Fire Blast", "Waterfall",
    "Clamp", "Swift", "Skull Bash", "Spike Cannon",
    "Constrict", "Amnesia", "Kinesis", "Soft-Boiled",
    "High Jump Kick", "Glare", "Dream Eater", "Poison Gas",
    "Barrage", "Leech Life", "Lovely Kiss", "Sky Attack",
    "Transform", "Bubble", "Dizzy Punch", "Spore",
    "Flash", "Psywave", "Splash", "Acid Armor",
    "Crabhammer", "Explosion", "Fury Swipes", "Bonemerang",
    "Rest", "Rock Slide", "Hyper Fang", "Sharpen",
    "Conversion", "Tri Attack", "Super Fang", "Slash",
    "Substitute", "Struggle", "Sketch", "Triple Kick",
    "Thief", "Spider Web", "Mind Reader", "Nightmare",
    "Flame Wheel", "Snore", "Curse", "Flail",
    "Conversion 2", "Aeroblast", "Cotton Spore", "Reversal",
    "Spite", "Powder Snow", "Protect", "Mach Punch",
    "Scary Face", "Feint Attack", "Sweet Kiss", "Belly Drum",
    "Sludge Bomb", "Mud-Slap", "Octazooka", "Spikes",
    "Zap Cannon", "Foresight", "Destiny Bond", "Perish Song",
    "Icy Wind", "Detect", "Bone Rush", "Lock-On",
    "Outrage", "Sandstorm", "Giga Drain", "Endure",
    "Charm", "Rollout", "False Swipe", "Swagger",
    "Milk Drink", "Spark", "Fury Cutter", "Steel Wing",
    "Mean Look", "Attract", "Sleep Talk", "Heal Bell",
    "Return", "Present", "Frustration", "Safeguard",
    "Pain Split", "Sacred Fire", "Magnitude", "Dynamic Punch",
    "Megahorn", "Dragon Breath", "Baton Pass", "Encore",
    "Pursuit", "Rapid Spin", "Sweet Scent", "Iron Tail",
    "Metal Claw", "Vital Throw", "Morning Sun", "Synthesis",
    "Moonlight", "Hidden Power", "Cross Chop", "Twister",
    "Rain Dance", "Sunny Day", "Crunch", "Mirror Coat",
    "Psych Up", "Extreme Speed", "Ancient Power", "Shadow Ball",
    "Future Sight", "Rock Smash", "Whirlpool", "Beat Up",
    "Fake Out", "Uproar", "Stockpile", "Spit Up",
    "Swallow", "Heat Wave", "Hail", "Torment",
    "Flatter", "Will-O-Wisp", "Memento", "Facade",
    "Focus Punch", "Smelling Salts", "Follow Me", "Nature Power",
    "Charge", "Taunt", "Helping Hand", "Trick",
    "Role Play", "Wish", "Assist", "Ingrain",
    "Superpower", "Magic Coat", "Recycle", "Revenge",
    "Brick Break", "Yawn", "Knock Off", "Endeavor",
    "Eruption", "Skill Swap", "Imprison", "Refresh",
    "Grudge", "Snatch", "Secret Power", "Dive",
    "Arm Thrust", "Camouflage", "Tail Glow", "Luster Purge",
    "Mist Ball", "Feather Dance", "Teeter Dance", "Blaze Kick",
    "Mud Sport", "Ice Ball", "Needle Arm", "Slack Off",
    "Hyper Voice", "Poison Fang", "Crush Claw", "Blast Burn",
    "Hydro Cannon", "Meteor Mash", "Astonish", "Weather Ball",
    "Aromatherapy", "Fake Tears", "Air Cutter", "Overheat",
    "Odor Sleuth", "Rock Tomb", "Silver Wind", "Metal Sound",
    "Grass Whistle", "Tickle", "Cosmic Power", "Water Spout",
    "Signal Beam", "Shadow Punch", "Extrasensory", "Sky Uppercut",
    "Sand Tomb", "Sheer Cold", "Muddy Water", "Bullet Seed",
    "Aerial Ace", "Icicle Spear", "Iron Defense", "Block",
    "Howl", "Dragon Claw", "Frenzy Plant", "Bulk Up",
    "Bounce", "Mud Shot", "Poison Tail", "Covet",
    "Volt Tackle", "Magical Leaf", "Water Sport", "Calm Mind",
    "Leaf Blade", "Dragon Dance", "Rock Blast", "Shock Wave",
    "Water Pulse", "Doom Desire", "Psycho Boost",
};

static const char *const item_names[] = {
    "Empty", "Master Ball", "Ultra Ball",
    "Great Ball", "Poke Ball", "Safari Ball",
    "Net Ball", "Dive Ball", "Nest Ball",
    "Repeat Ball", "Timer Ball", "Luxury Ball",
    "Premier Ball", "Potion", "Antidote",
    "Burn Heal", "Ice Heal", "Awakening",
    "Parlyz Heal", "Full Restore", "Max Potion",
    "Hyper Potion", "Super Potion", "Full Heal",
    "Revive", "Max Revive", "Fresh Water",
    "Soda Pop", "Lemonade", "Moomoo Milk",
    "EnergyPowder", "Energy Root", "Heal Powder",
    "Revival Herb", "Ether", "Max Ether",
    "Elixir", "Max Elixir", "Lava Cookie",
    "Blue Flute", "Yellow Flute", "Red Flute",
    "Black Flute", "White Flute", "Berry Juice",
    "Sacred Ash", "Shoal Salt", "Shoal Shell",
    "Red Shard", "Blue Shard", "Yellow Shard",
    "Green Shard", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "HP Up", "Protein", "Iron",
    "Carbos", "Calcium", "Rare Candy",
    "PP Up", "Zinc", "PP Max",
    "???", "Guard Spec.", "Dire Hit",
    "X Attack", "X Defend", "X Speed",
    "X Accuracy", "X Special", "Poke Doll",
    "Fluffy Tail", "???", "Super Repel",
    "Max Repel", "Escape Rope", "Repel",
    "???", "???", "???",
    "???", "???", "???",
    "Sun Stone", "Moon Stone", "Fire Stone",
    "Thunder Stone", "Water Stone", "Leaf Stone",
    "???", "???", "???",
    "???", "TinyMushroom", "Big Mushroom",
    "???", "Pearl", "Big Pearl",
    "Stardust", "Star Piece", "Nugget",
    "Heart Scale", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "???", "Orange Mail", "Harbor Mail",
    "Glitter Mail", "Mech Mail", "Wood Mail",
    "Wave Mail", "Bead Mail", "Shadow Mail",
    "Tropic Mail", "Dream Mail", "Fab Mail",
    "Retro Mail", "Cheri Berry", "Chesto Berry",
    "Pecha Berry", "Rawst Berry", "Aspear Berry",
    "Leppa Berry", "Oran Berry", "Persim Berry",
    "Lum Berry", "Sitrus Berry", "Figy Berry",
    "Wiki Berry", "Mago Berry", "Aguav Berry",
    "Iapapa Berry", "Razz Berry", "Bluk Berry",
    "Nanab Berry", "Wepear Berry", "Pinap Berry",
    "Pomeg Berry", "Kelpsy Berry", "Qualot Berry",
    "Hondew Berry", "Grepa Berry", "Tamato Berry",
    "Cornn Berry", "Magost Berry", "Rabuta Berry",
    "Nomel Berry", "Spelon Berry", "Pamtre Berry",
    "Watmel Berry", "Durin Berry", "Belue Berry",
    "Liechi Berry", "Ganlon Berry", "Salac Berry",
    "Petaya Berry", "Apicot Berry", "Lansat Berry",
    "Starf Berry", "Enigma Berry", "???",
    "???", "???", "BrightPowder",
    "White Herb", "Macho Brace", "Exp. Share",
    "Quick Claw", "Soothe Bell", "Mental Herb",
    "Choice Band", "King's Rock", "SilverPowder",
    "Amulet Coin", "Cleanse Tag", "Soul Dew",
    "DeepSeaTooth", "DeepSeaScale", "Smoke Ball",
    "Everstone", "Focus Band", "Lucky Egg",
    "Scope Lens", "Metal Coat", "Leftovers",
    "Dragon Scale", "Light Ball", "Soft Sand",
    "Hard Stone", "Miracle Seed", "BlackGlasses",
    "Black Belt", "Magnet", "Mystic Water",
    "Sharp Beak", "Poison Barb", "NeverMeltIce",
    "Spell Tag", "TwistedSpoon", "Charcoal",
    "Dragon Fang", "Silk Scarf", "Up-Grade",
    "Shell Bell", "Sea Incense", "Lax Incense",
    "Lucky Punch", "Metal Powder", "Thick Club",
    "Stick", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "???", "???", "???",
    "???", "???", "Red Scarf",
    "Blue Scarf", "Pink Scarf", "Green Scarf",
    "Yellow Scarf", "Mach Bike", "Coin Case",
    "Itemfinder", "Old Rod", "Good Rod",
    "Super Rod", "S.S. Ticket", "Contest Pass",
    "???", "Wailmer Pail", "Devon Goods",
    "Soot Sack", "Basement Key", "Acro Bike",
    "Pokeblock Case", "Letter", "Eon Ticket",
    "Red Orb", "Blue Orb", "Scanner",
    "Go-Goggles", "Meteorite", "Rm. 1 Key",
    "Rm. 2 Key", "Rm. 4 Key", "Rm. 6 Key",
    "Storage Key", "Root Fossil", "Claw Fossil",
    "Devon Scope", "TM01", "TM02",
    "TM03", "TM04", "TM05",
    "TM06", "TM07", "TM08",
    "TM09", "TM10", "TM11",
    "TM12", "TM13", "TM14",
    "TM15", "TM16", "TM17",
    "TM18", "TM19", "TM20",
    "TM21", "TM22", "TM23",
    "TM24", "TM25", "TM26",
    "TM27", "TM28", "TM29",
    "TM30", "TM31", "TM32",
    "TM33", "TM34", "TM35",
    "TM36", "TM37", "TM38",
    "TM39", "TM40", "TM41",
    "TM42", "TM43", "TM44",
    "TM45", "TM46", "TM47",
    "TM48", "TM49", "TM50",
    "HM01", "HM02", "HM03",
    "HM04", "HM05", "HM06",
    "HM07", "HM08", "???",
    "???", "Oak's Parcel", "Poke Flute",
    "Secret Key", "Bike Voucher", "Gold Teeth",
    "Old Amber", "Card Key", "Lift Key",
    "Helix Fossil", "Dome Fossil", "Silph Scope",
    "Bicycle", "Town Map", "Vs. Seeker",
    "Fame Checker", "TM Case", "Berry Pouch",
    "Teachy TV", "Tri-Pass", "Rainbow Pass",
    "Tea", "MysticTicket", "AuroraTicket",
    "Powder Jar", "Ruby", "Sapphire",
    "Magma Emblem", "Old Sea Map",
};

static const char *const species_names[] = {
    "Bulbasaur", "Ivysaur", "Venusaur", "Charmander",
    "Charmeleon", "Charizard", "Squirtle", "Wartortle",
    "Blastoise", "Caterpie", "Metapod", "Butterfree",
    "Weedle", "Kakuna", "Beedrill", "Pidgey",
    "Pidgeotto", "Pidgeot", "Rattata", "Raticate",
    "Spearow", "Fearow", "Ekans", "Arbok",
    "Pikachu", "Raichu", "Sandshrew", "Sandslash",
    "Nidoran(F)", "Nidorina", "Nidoqueen", "Nidoran(M)",
    "Nidorino", "Nidoking", "Clefairy", "Clefable",
    "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff",
    "Zubat", "Golbat", "Oddish", "Gloom",
    "Vileplume", "Paras", "Parasect", "Venonat",
    "Venomoth", "Diglett", "Dugtrio", "Meowth",
    "Persian", "Psyduck", "Golduck", "Mankey",
    "Primeape", "Growlithe", "Arcanine", "Poliwag",
    "Poliwhirl", "Poliwrath", "Abra", "Kadabra",
    "Alakazam", "Machop", "Machoke", "Machamp",
    "Bellsprout", "Weepinbell", "Victreebel", "Tentacool",
    "Tentacruel", "Geodude", "Graveler", "Golem",
    "Ponyta", "Rapidash", "Slowpoke", "Slowbro",
    "Magnemite", "Magneton", "Farfetch'd", "Doduo",
    "Dodrio", "Seel", "Dewgong", "Grimer",
    "Muk", "Shellder", "Cloyster", "Gastly",
    "Haunter", "Gengar", "Onix", "Drowzee",
    "Hypno", "Krabby", "Kingler", "Voltorb",
    "Electrode", "Exeggcute", "Exeggutor", "Cubone",
    "Marowak", "Hitmonlee", "Hitmonchan", "Lickitung",
    "Koffing", "Weezing", "Rhyhorn", "Rhydon",
    "Chansey", "Tangela", "Kangaskhan", "Horsea",
    "Seadra", "Goldeen", "Seaking", "Staryu",
    "Starmie", "Mr. Mime", "Scyther", "Jynx",
    "Electabuzz", "Magmar", "Pinsir", "Tauros",
    "Magikarp", "Gyarados", "Lapras", "Ditto",
    "Eevee", "Vaporeon", "Jolteon", "Flareon",
    "Porygon", "Omanyte", "Omastar", "Kabuto",
    "Kabutops", "Aerodactyl", "Snorlax", "Articuno",
    "Zapdos", "Moltres", "Dratini", "Dragonair",
    "Dragonite", "Mewtwo", "Mew", "Chikorita",
    "Bayleef", "Meganium", "Cyndaquil", "Quilava",
    "Typhlosion", "Totodile", "Croconaw", "Feraligatr",
    "Sentret", "Furret", "Hoothoot", "Noctowl",
    "Ledyba", "Ledian", "Spinarak", "Ariados",
    "Crobat", "Chinchou", "Lanturn", "Pichu",
    "Cleffa", "Igglybuff", "Togepi", "Togetic",
    "Natu", "Xatu", "Mareep", "Flaaffy",
    "Ampharos", "Bellossom", "Marill", "Azumarill",
    "Sudowoodo", "Politoed", "Hoppip", "Skiploom",
    "Jumpluff", "Aipom", "Sunkern", "Sunflora",
    "Yanma", "Wooper", "Quagsire", "Espeon",
    "Umbreon", "Murkrow", "Slowking", "Misdreavus",
    "Unown", "Wobbuffet", "Girafarig", "Pineco",
    "Forretress", "Dunsparce", "Gligar", "Steelix",
    "Snubbull", "Granbull", "Qwilfish", "Scizor",
    "Shuckle", "Heracross", "Sneasel", "Teddiursa",
    "Ursaring", "Slugma", "Magcargo", "Swinub",
    "Piloswine", "Corsola", "Remoraid", "Octillery",
    "Delibird", "Mantine", "Skarmory", "Houndour",
    "Houndoom", "Kingdra", "Phanpy", "Donphan",
    "Porygon2", "Stantler", "Smeargle", "Tyrogue",
    "Hitmontop", "Smoochum", "Elekid", "Magby",
    "Miltank", "Blissey", "Raikou", "Entei",
    "Suicune", "Larvitar", "Pupitar", "Tyranitar",
    "Lugia", "Ho-Oh", "Celebi", "Treecko",
    "Grovyle", "Sceptile", "Torchic", "Combusken",
    "Blaziken", "Mudkip", "Marshtomp", "Swampert",
    "Poochyena", "Mightyena", "Zigzagoon", "Linoone",
    "Wurmple", "Silcoon", "Beautifly", "Cascoon",
    "Dustox", "Lotad", "Lombre", "Ludicolo",
    "Seedot", "Nuzleaf", "Shiftry", "Taillow",
    "Swellow", "Wingull", "Pelipper", "Ralts",
    "Kirlia", "Gardevoir", "Surskit", "Masquerain",
    "Shroomish", "Breloom", "Slakoth", "Vigoroth",
    "Slaking", "Nincada", "Ninjask", "Shedinja",
    "Whismur", "Loudred", "Exploud", "Makuhita",
    "Hariyama", "Azurill", "Nosepass", "Skitty",
    "Delcatty", "Sableye", "Mawile", "Aron",
    "Lairon", "Aggron", "Meditite", "Medicham",
    "Electrike", "Manectric", "Plusle", "Minun",
    "Volbeat", "Illumise", "Roselia", "Gulpin",
    "Swalot", "Carvanha", "Sharpedo", "Wailmer",
    "Wailord", "Numel", "Camerupt", "Torkoal",
    "Spoink", "Grumpig", "Spinda", "Trapinch",
    "Vibrava", "Flygon", "Cacnea", "Cacturne",
    "Swablu", "Altaria", "Zangoose", "Seviper",
    "Lunatone", "Solrock", "Barboach", "Whiscash",
    "Corphish", "Crawdaunt", "Baltoy", "Claydol",
    "Lileep", "Cradily", "Anorith", "Armaldo",
    "Feebas", "Milotic", "Castform", "Kecleon",
    "Shuppet", "Banette", "Duskull", "Dusclops",
    "Tropius", "Chimecho", "Absol", "Wynaut",
    "Snorunt", "Glalie", "Spheal", "Sealeo",
    "Walrein", "Clamperl", "Huntail", "Gorebyss",
    "Relicanth", "Luvdisc", "Bagon", "Shelgon",
    "Salamence", "Beldum", "Metang", "Metagross",
    "Regirock", "Regice", "Registeel", "Latias",
    "Latios", "Kyogre", "Groudon", "Rayquaza",
    "Jirachi", "Deoxys",
};

static const char *const colosseum_item_names[] = {
    "Jail Key", "Elevator Key", "Small Tablet",
    "F-Disk", "R-Disk", "L-Disk",
    "D-Disk", "U-Disk", "Subway Key",
    "Maingate Key", "Card Key", "Down St. Key",
    "DNA Sample", "DNA Sample", "DNA Sample",
    "DNA Sample", "DNA Sample", "DNA Sample",
    "DNA Sample", "DNA Sample", "DNA Sample",
    "DNA Sample", "DNA Sample", "DNA Sample",
    "DNA Sample", "DNA Sample", "DNA Sample",
    "DNA Sample", "DNA Sample", "DNA Sample",
    "Data ROM", "Steel Teeth", "Gear",
    "Red ID Badge", "Grn ID Badge", "Blu ID Badge",
    "Ylw ID Badge", "Time Flute", "Ein File S",
    "Ein File H", "Ein File C", "Ein File P",
    "Cologne Case", "Joy Scent", "Excite Scent",
    "Vivid Scent", "Powerup Part", "Ein File F",
};

static const char *const xd_item_names[] = {
    "Safe Key", "Elevator Key", "Bonsly Card",
    "Machine Part", "Gonzap's Key", "Data ROM",
    "ID Card", "Music Disc", "System Lever",
    "Mayor's Note", "Miror Radar", "Poke Snack",
    "Cologne Case", "Joy Scent", "Excite Scent",
    "Vivid Scent", "Sun Shard", "Moon Shard",
    "Bonsly Photo", "Cry Analyzer", "???",
    "???", "???", "Krane Memo 1",
    "Krane Memo 2", "Krane Memo 3", "Krane Memo 4",
    "Krane Memo 5", "Voice Case 1", "Voice Case 2",
    "Voice Case 3", "Voice Case 4", "Voice Case 5",
    "Disc Case", "Battle CD 01", "Battle CD 02",
    "Battle CD 03", "Battle CD 04", "Battle CD 05",
    "Battle CD 06", "Battle CD 07", "Battle CD 08",
    "Battle CD 09", "Battle CD 10", "Battle CD 11",
    "Battle CD 12", "Battle CD 13", "Battle CD 14",
    "Battle CD 15", "Battle CD 16", "Battle CD 17",
    "Battle CD 18", "Battle CD 19", "Battle CD 20",
    "Battle CD 21", "Battle CD 22", "Battle CD 23",
    "Battle CD 24", "Battle CD 25", "Battle CD 26",
    "Battle CD 27", "Battle CD 28", "Battle CD 29",
    "Battle CD 30", "Battle CD 31", "Battle CD 32",
    "Battle CD 33", "Battle CD 34", "Battle CD 35",
    "Battle CD 36", "Battle CD 37", "Battle CD 38",
    "Battle CD 39", "Battle CD 40", "Battle CD 41",
    "Battle CD 42", "Battle CD 43", "Battle CD 44",
    "Battle CD 45", "Battle CD 46", "Battle CD 47",
    "Battle CD 48", "Battle CD 49", "Battle CD 50",
    "Battle CD 51", "Battle CD 52", "Battle CD 53",
    "Battle CD 54", "Battle CD 55", "Battle CD 56",
    "Battle CD 57", "Battle CD 58", "Battle CD 59",
    "Battle CD 60",
};

static const char *const decoration_names[] = {
    "-", "Small Desk", "Pokemon Desk",
    "Heavy Desk", "Ragged Desk", "Comfort Desk",
    "Pretty Desk", "Brick Desk", "Camp Desk",
    "Hard Desk", "Small Chair", "Pokemon Chair",
    "Heavy Chair", "Pretty Chair", "Comfort Chair",
    "Ragged Chair", "Brick Chair", "Camp Chair",
    "Hard Chair", "Red Plant", "Tropical Plant",
    "Pretty Flowers", "Colorful Plant", "Big Plant",
    "Gorgeous Plant", "Red Brick", "Yellow Brick",
    "Blue Brick", "Red Balloon", "Blue Balloon",
    "Yellow Balloon", "Red Tent", "Blue Tent",
    "Solid Board", "Slide", "Fence Length",
    "Fence Width", "Tire", "Stand",
    "Mud Ball", "Breakable Door", "Sand Ornament",
    "Silver Shield", "Gold Shield", "Glass Ornament",
    "TV", "Round TV", "Cute TV",
    "Glitter Mat", "Jump Mat", "Spin Mat",
    "C Low Note Mat", "D Note Mat", "E Note Mat",
    "F Note Mat", "G Note Mat", "A Note Mat",
    "B Note Mat", "C High Note Mat", "Surf Mat",
    "Thunder Mat", "Fire Blast Mat", "Powder Snow Mat",
    "Attract Mat", "Fissure Mat", "Spikes Mat",
    "Ball Poster", "Green Poster", "Red Poster",
    "Blue Poster", "Cute Poster", "Pika Poster",
    "Long Poster", "Sea Poster", "Sky Poster",
    "Kiss Poster", "Pichu Doll", "Pikachu Doll",
    "Marill Doll", "Togepi Doll", "Cyndaquil Doll",
    "Chikorita Doll", "Totodile Doll", "Jigglypuff Doll",
    "Meowth Doll", "Clefairy Doll", "Ditto Doll",
    "Smoochum Doll", "Treecko Doll", "Torchic Doll",
    "Mudkip Doll", "Duskull Doll", "Wynaut Doll",
    "Baltoy Doll", "Kecleon Doll", "Azurill Doll",
    "Skitty Doll", "Swablu Doll", "Gulpin Doll",
    "Lotad Doll", "Seedot Doll", "Pika Cushion",
    "Round Cushion", "Kiss Cushion", "Zigzag Cushion",
    "Spin Cushion", "Diamond Cushion", "Ball Cushion",
    "Grass Cushion", "Fire Cushion", "Water Cushion",
    "Snorlax Doll", "Rhydon Doll", "Lapras Doll",
    "Venusaur Doll", "Charizard Doll", "Blastoise Doll",
    "Wailmer Doll", "Regirock Doll", "Regice Doll",
    "Registeel Doll",
};

static const char *const trendy_word_names[] = {
    "KTHXBYE", "YESSIR", "AVANTGARDE", "COUPLE",
    "MUCHOBLIGED", "YEEHAW", "MEGA", "ONEHITKO",
    "DESTINY", "CANCEL", "NEW", "FLATTEN",
    "KIDDING", "LOSER", "LOSING", "HAPPENING",
    "HIPAND", "SHAKE", "SHADY", "UPBEAT",
    "MODERN", "SMELLYA", "BANG", "KNOCKOUT",
    "HASSLE", "WINNER", "FEVER", "WANNABE",
    "BABY", "HEART", "OLD", "YOUNG",
    "UGLY",
};

static const char *const trainer_hill_mode_names[] = {
    "Normal", "Variety", "Unique", "Expert",
};

#define COUNT(a) ((unsigned)(sizeof (a) / sizeof (a)[0]))
#define CXD_ITEM_BASE 500u

const char *gen3_move_name(uint16_t move_id) {
    return move_id < COUNT(move_names) ? move_names[move_id] : "Unknown move";
}

const char *gen3_item_name(uint16_t item_id) {
    return item_id < COUNT(item_names) ? item_names[item_id] : "???";
}

/*
 * Colosseum and XD share the cartridge item ids and add their own above 500.
 * Naming one of those through gen3_item_name would report "???" for every key
 * item those games have.
 */
const char *gen3_item_name_for(Gen3SaveKind kind, uint16_t item_id) {
    if (item_id >= CXD_ITEM_BASE) {
        const unsigned offset = (unsigned)item_id - CXD_ITEM_BASE;
        if (kind == GEN3_KIND_COLOSSEUM && offset < COUNT(colosseum_item_names))
            return colosseum_item_names[offset];
        if (kind == GEN3_KIND_XD && offset < COUNT(xd_item_names))
            return xd_item_names[offset];
        return "???";
    }
    return gen3_item_name(item_id);
}

/*
 * Stepping an item id, for a save of a given kind.
 *
 * The ids are not one range. Every game shares the cartridge items at 0..376,
 * and Colosseum and XD put their own - the key items, the colognes, the discs -
 * at 500 and up, leaving 377..499 meaning nothing at all.
 *
 * The inventory editor used to clamp to 0..376 regardless of kind, so a single
 * press on any Colosseum key item dropped it from 500-something to 376 and the
 * item was gone. Walking the two ranges as one list keeps every id reachable,
 * never lands on one that is not an item, and cannot destroy the id it started
 * from.
 */
static unsigned item_id_ordinal_max(Gen3SaveKind kind) {
    if (kind == GEN3_KIND_COLOSSEUM) return COUNT(item_names) - 1u + COUNT(colosseum_item_names);
    if (kind == GEN3_KIND_XD) return COUNT(item_names) - 1u + COUNT(xd_item_names);
    return COUNT(item_names) - 1u;
}

/* Position of an id in that combined list. An id in the dead range, which a
 * corrupt save can hold, answers with the last cartridge item. */
static unsigned item_id_to_ordinal(uint16_t item_id) {
    if (item_id < COUNT(item_names)) return item_id;
    if (item_id < CXD_ITEM_BASE) return COUNT(item_names) - 1u;
    return COUNT(item_names) + ((unsigned)item_id - CXD_ITEM_BASE);
}

static uint16_t item_id_from_ordinal(unsigned ordinal) {
    if (ordinal < COUNT(item_names)) return (uint16_t)ordinal;
    return (uint16_t)(CXD_ITEM_BASE + (ordinal - COUNT(item_names)));
}

uint16_t gen3_item_id_step(Gen3SaveKind kind, uint16_t item_id, int direction, unsigned step) {
    const unsigned last = item_id_ordinal_max(kind);
    long long ordinal = (long long)item_id_to_ordinal(item_id) +
                        (long long)direction * (long long)step;
    if (ordinal < 0) ordinal = 0;
    if (ordinal > (long long)last) ordinal = (long long)last;
    return item_id_from_ordinal((unsigned)ordinal);
}

const char *gen3_decoration_name(uint8_t decoration_id) {
    return decoration_id < COUNT(decoration_names) ? decoration_names[decoration_id] : "???";
}

/* Easy Chat words, kept as PKHeX spells them - see the note at the top. */
const char *gen3_trendy_word_name(unsigned word) {
    return word < COUNT(trendy_word_names) ? trendy_word_names[word] : "?";
}

const char *gen3_trainer_hill_mode_name(unsigned mode) {
    return mode < COUNT(trainer_hill_mode_names) ? trainer_hill_mode_names[mode] : "?";
}

const char *gen3_species_name(uint16_t internal_species) {
    const unsigned national = gen3_species_national(internal_species);
    if (national < 1u || national > COUNT(species_names)) return "Unknown";
    return species_names[national - 1u];
}
